### PR TITLE
Added bottom center position

### PR DESCRIPTION
**Pull request by Aj1402**

### CODE REVIEW

**Comment by Aj1402** [comment]
Added both top center and bottom center positions.

**Comment by Aj1402** [comment]
Does that mean i need to add some more tests?

**Comment by Aj1402** [comment]
@dennybiasiolli Alright changes done, should I create a new PR?

**Comment by dennybiasiolli** [comment]
Great, thanks! Now you can merge all your commits into a single one:

- `Added top center and bottom center positioning` with code change and tests

Or two commits if you want:

- The first with `Added top center positioning` with code change and tests for that
- The second with `Added bottom center position` with code change and tests for that

Thanks @Aj1402! 😃

**Comment by dennybiasiolli** [comment]
@Aj1402 no, this PR is ok, but can you please please merge all the commits, adding tests for your edits?

**Comment by Aj1402** [comment]
@dennybiasiolli I haven't added tests yet, so ill merge them as soon as I am done with tests

**Pull request closed without merging**
