### PR TITLE
AlertContainer: adding onCloseAlert callback props to the component

### PR DESCRIPTION
**Pull request by dennybiasiolli**
Ref. #24

### CODE REVIEW

**Comment by schiehll** [comment]
Hey @dennybiasiolli ,

Thank you for that! And sorry about the delay.

The code looks good, but I don't know if it's the right approach, maybe we can make the API look something like this:

```js
this.msg.show('message', {
...otherOptions, 
onClose: () => {}
})
```
That way we can get a callback for a specific alert, because I don't know if it would be of much help to get the list of closed alerts in a global listener since we don't return the id of the alert when the `show/success/error/info` methods are called, so the only way to check if it's a specific alert would be to check the message, but the message could be a react component too and those are more complicated than a simple `===`.

What do you think?

I don't know, maybe I'm missing something here and with the API that you are adding in this PR there is a easy way to check for a specific alert?

**Comment by dennybiasiolli** [comment]
@schiehll you're right, your solution it's better than mine, I'm changing the code in order to have the `onClose` option in `show` function. Thanks for the suggestion! 😉

**Comment by schiehll** [comment]
That was fast! Thank you so much!

Looks good, I will merge it and release a new version to npm later today.

**Comment by dennybiasiolli** [comment]
Thanks @schiehll, when released I think we can close #25, right?

**Comment by schiehll** [comment]
Sure! As soon as I release it I will close it!

**Pull request merged**
