### PR TITLE
Added top center and bottom center positions

### PR DESCRIPTION
**Pull request by Aj1402**
Added new positions as requested along with tests and new snapshots.

### CODE REVIEW

**Comment by Aj1402** [comment]
@dennybiasiolli I have made all the changes that were requested. Hope you can review them!

**Comment by dennybiasiolli** [comment]
@schiehll I think this PR is mergeable in master, what do you think?

**Comment by schiehll** [comment]
@dennybiasiolli thanks for the help!
@Aj1402 thank you! Great work! Sorry about the delay.

I'll merge it and will be releasing a new version on npm ASAP.

**Comment by Aj1402** [comment]
@schiehll Thanks a lot!

_Sent from my Lenovo A6020a46 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
