### PR TITLE
Fix transition scale bug

### LINKED ISSUE #108: Incompatibility with react-select
When using both react-select and react-alert in the same component, react-alert shows the alert twice instead of once.

```
import React, { Component } from 'react'
import Select from 'react-select';
import { withAlert } from 'react-alert'

class MyComponent extends Component {
    constructor (props) {
        super(props);

        this.flash=this.flash.bind(this);

    }

    flash()
    {
        this.props.alert.error("HA");
    }

    render () {

        return (
            <div>
                <Select/>
                <a onClick={this.flash}>Click me</a>
            </div>
        );
    }
}

export default withAlert(MyComponent);
```

React select lib: https://github.com/JedWatson/react-select

### PR DESCRIPTION
**Pull request by besLisbeth**
Resolve #108

### CODE REVIEW

**Comment by schiehll** [comment]
Thank you as always @besLisbeth!

**Comment by schiehll** [comment]
Oh, actually, after testing it, looks like it broke the scale transition, will revert it.

**Comment by besLisbeth** [comment]
Oh no, I also tested it and did not find anything. Sorry then(

**Comment by schiehll** [comment]
No worries! I've tested it in the codesandbox and it broke the scale transition when the alert is leaving. Reverting it fixed. BUT looks like it fix only when there's more than one alert, when there's only one it's still broken. 🤔

We should investigate it.

**Comment by schiehll** [comment]
I've just tested the v5.1.0 (before the addition of support for multiple positions) and it worked...looks like it's broken since v5.2.0. Can you take a look in the code you added in that release and see what could be causing it?

**Comment by besLisbeth** [comment]
Yes, I found it. The problem with animation for the ONE leaving alert caused by condition rendering - react unmount TransitionGroup faster than it shows the exiting animation

**Comment by schiehll** [comment]
Yeah, that make sense! Did you thought in any possible solution?

**Comment by besLisbeth** [comment]
Yes! I move TransitionGroup higher on the DOM tree - to be stable and above the conditionally rendered Wrappers. But still, have problems with exiting animation - I'm trying to find the solution with 'react-select'

**Comment by besLisbeth** [comment]
I can't understand what caused such strange behaviour

**Comment by schiehll** [comment]
I'm not so worried about the `react-select` thing, for all we know it can be a problem with them, I'm more worried with the broken transition thing.

**Comment by schiehll** [comment]
Moving it higher in the tree makes it work not considering the `react-select` issue?

**Comment by besLisbeth** [comment]
It's strange. Now it works for the last alert in the array. But not for others.

**Comment by besLisbeth** [comment]
The alerts between 1 and alerts.length are not firing onExit event

**Comment by schiehll** [comment]
Weird stuff hahah can I see some code?

**Comment by besLisbeth** [comment]
Try to pull from [there](https://github.com/besLisbeth/react-alert/tree/bug/weird-transition) and not include 'react-select'

**Comment by besLisbeth** [comment]
Code can be dirty)

**Comment by schiehll** [comment]
that's totally fine! will take a look and see if I can help somehow, thanks!

**Comment by besLisbeth** [comment]
Thank you!

**Comment by schiehll** [comment]
Hey @besLisbeth! I took a look in the code and couldn't find a solution. So for now I will revert the changes of v5.2, so you would only be able to use multiple alerts via multiple Contexts (unless you stay in v5.2.0 - v5.3.1).

If you find a solution, we can put the feature back.

**Comment by besLisbeth** [comment]
Sure, thank you. Sorry that I caused such inconvenience(

I'll try to find a solution.

**Comment by schiehll** [comment]
No worries! If you find a solution you are more then welcome to submit a new PR!

**Pull request merged**
